# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop_core.model.auth


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', shop_core.model.auth.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEmails',
            fields=[
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='shop_core.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='primary_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_core.ProfileEmails'),
        ),
    ]
